spring.application.name=PrompLab
server.port=8081

# DATABASE CONNECTION (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/promptLab_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Disabled OSIV to prevent connection pool exhaustion and clear the startup warning
spring.jpa.open-in-view=false

# SPRING SECURITY CREDENTIALS
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# SPRING MAIL CONFIGURATION (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=promptlab.developer@gmail.com
spring.mail.password=@promptLab@123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true